language: node_js

node_js:
  - "5.0"

script:
  # Ignoring the following commands since they fail without resources
  # Resources are being kept private until the release
  # npm run build:ios
  # npm run build:android
  - npm run lint
  # - npm run flow
  # - npm run test
